import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

import Navigation from './components/Navigation';
import Footer from './components/Footer';
import Card from './components/Card';
import ClientWrapper from './components/ClientWrapper';
import './global.css';
export const metadata = {
  title: 'Supalerk - Frontend 038',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap" rel="stylesheet" />
      </head>
      
      <body className="antialiased bg-gradient-to-br from-white via-purple-50 to-pink-100 text-gray-800">
        <div className="container-fluid px-0">
          <div className="row m-0">
            <div className="col-12 p-0">
              <ClientWrapper>{children}</ClientWrapper>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}