import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

import Navigation from './components/Navigation';
import Footer from './components/Footer';
import Card from './components/Card';
import ClientWrapper from './components/ClientWrapper'; // สร้าง component client ไว้ควบคุมเงื่อนไข

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased bg-gradient-to-br from-white via-purple-50 to-pink-100 text-gray-800">
        <div className="container-fluid px-0">
          <div className="row m-0">
            <div className="col-12 p-0">
              <ClientWrapper>{children}</ClientWrapper>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
