import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

import Navigation from "./components/Navigation";
import Footer from "./components/Footer";
import Card from './components/Card';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="container-fluid">
          <div className="row">
            <div className="col-12">
              <Navigation />
              {children}
              <Card />
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
